spring.application.name=ensino

spring.datasource.url=jdbc:h2:file:./data/spring-security
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
api.security.token.secret=minha-chave-muito-secreta-e-ultra-segura-com-mais-de-32-caracteres

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
